AllCops:
  NewCops: enable

plugins:
  - rubocop-rake
  - rubocop-rspec

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - "features/step_definitions/**/*.rb"

Style/StringLiterals:
  EnforcedStyle: double_quotes
